all:
	clang++ -std=c++11 socks_server.cpp -o socks_server -I /usr/local/include -L /usr/local/lib -Wall -pedantic -pthread -lboost_system
	clang++ -std=c++11 console.cpp -o hw4.cgi -I /usr/local/include -L /usr/local/lib -Wall -pedantic -pthread -lboost_system
